#!/usr/bin/env bash
# Update package list, install nginx, configure it, and restart the service

apt-get update -y && apt-get install -y nginx

cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOL

service nginx restart
