#!/usr/bin/env bash
# Update and install nginx, configure, and restart

apt-get update -y && apt-get install -y nginx

echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files $uri $uri/ =404;
    }
}' > /etc/nginx/sites-available/default

service nginx restart
