#!/usr/bin/env bash
#The script explictly sets nginx listen on port 80 and then restart it to ensure the new configuration is active

apt-get update

apt-get install -y nginx


sudo bash -c 'cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOL'

# Restart Nginx to apply the configuration
service nginx restart
